
services:
  # PostgreSQL для user-service
  postgres:
    image: postgres:15
    container_name: aston-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Пробрасываем порт 5433 на хосте -> 5432 внутри контейнера
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aston-network

  # Zookeeper (нужен для Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: aston-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - aston-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: aston-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - aston-network

volumes:
  postgres-data:

networks:
  aston-network:
    driver: bridge